---
collections:
  - name: ansible.utils
  - name: ansible.netcommon
  - name: cisco.ios
  - name: junipernetworks.junos
  - name: community.network
  - name: community.routeros
  - name: netbox.netbox