all:
  children:
    cisco_routers:
      hosts:
        HQ-CR-01:
          ansible_host: 192.168.10.11
        HQ-CR-02:
          ansible_host: 192.168.10.12

    cisco_switches:
      hosts:
        HQ-DSW-01:
          ansible_host: 192.168.10.21
        HQ-DSW-02:
          ansible_host: 192.168.10.22
        HQ-ASW-01:
          ansible_host: 192.168.10.31
        HQ-ASW-02:
          ansible_host: 192.168.10.32
        HQ-DMZ-SW01:
          ansible_host: 192.168.10.41

    pfsense:
      hosts:
        HQ-FW-EDGE01:
          ansible_host: 192.168.10.2

    juniper:
      hosts:
        HQ-EDG-PE01:
          ansible_host: 192.168.10.1

    mikrotik:
      hosts:
        PRZ-RTR-01:
          ansible_host: 203.0.113.2